
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const LOGOUT = "LOGOUT"

export const SELECT_CONVERSATION = "SELECT_CONVERSATION"
export const FETCH_CONVERSATION_REQUEST = "FETCH_CONVERSATION_REQUEST"
export const FETCH_CONVERSATION_SUCCESS = "FETCH_CONVERSATION_SUCCESS"
export const FETCH_CONVERSATION_FAILURE = "FETCH_CONVERSATION_FAILURE"
